navNode:
  ros__parameters:
    test: navNode
    paths_scan_all: |
      [
        {"x": 0.00, "y": 0.00, "z": 0.70, "label": "TakeOff","qrcode": ""},
        {"x":-0.25, "y": 0.75, "z": 0.80, "label": "A6"   ,"qrcode": ""},
        {"x":-0.25, "y": 0.75, "z": 1.20, "label": "A3"   ,"qrcode": ""},
        {"x":-0.25, "y": 1.25, "z": 1.20, "label": "A2"   ,"qrcode": ""},
        {"x":-0.25, "y": 1.25, "z": 0.80, "label": "A5"   ,"qrcode": ""},
        {"x":-0.25, "y": 1.75, "z": 0.80, "label": "A4"   ,"qrcode": ""},
        {"x":-0.25, "y": 1.75, "z": 1.20, "label": "A1"   ,"qrcode": ""},
        {"x": 0.75, "y": 2.75, "z": 0.70, "label": "UpSide1","qrcode": ""},
        {"x": 0.75, "y": 2.75, "z": 0.70, "label": "Landpos","qrcode": ""}
      ]


testNode:
  ros__parameters:
    test: testNode
    paths_scan_all: |
      [
        {"x": 0.00, "y": 0.00, "z": 0.70, "label": "TakeOff","qrcode": ""},
        {"x":-0.25, "y": 0.75, "z": 0.80, "label": "A6"   ,"qrcode": ""},
        {"x":-0.25, "y": 0.75, "z": 1.20, "label": "A3"   ,"qrcode": ""},
        {"x":-0.25, "y": 1.25, "z": 1.20, "label": "A2"   ,"qrcode": ""},
        {"x":-0.25, "y": 1.25, "z": 0.80, "label": "A5"   ,"qrcode": ""},
        {"x":-0.25, "y": 1.75, "z": 0.80, "label": "A4"   ,"qrcode": ""},
        {"x":-0.25, "y": 1.75, "z": 1.20, "label": "A1"   ,"qrcode": ""},
        {"x": 0.75, "y": 2.75, "z": 0.70, "label": "UpSide1","qrcode": ""},
        {"x": 0.75, "y": 2.75, "z": 0.70, "label": "Landpos","qrcode": ""}
      ]

# yaml文件内的 JSON string 不支持尾随逗号（trailing comma），这是很多开发者（包括老手）都踩过的坑。
# yaml文件内的 JSON string 不支持尾随逗号（trailing comma），这是很多开发者（包括老手）都踩过的坑。
# yaml文件内的 JSON string 不支持尾随逗号（trailing comma），这是很多开发者（包括老手）都踩过的坑。
