float64 pos_x
float64 pos_y
float64 pos_z
int64 confidence

float64 tof_z

# float64 pos_orient_x
# float64 pos_orient_y 
# float64 pos_orient_z
# float64 pos_orient_w 

# float64 vel_linear_x
# float64 vel_linear_y 
# float64 vel_linear_z
# float64 vel_angular_x 
# float64 vel_angular_y 
# float64 vel_angular_z 

# float64 acc_linear_x 
# float64 acc_linear_y 
# float64 acc_linear_z 
# float64 acc_angular_x 
# float64 acc_angular_y 
# float64 acc_angular_z 

# frame_id
# stamp