# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/focal/Desktop/2024_GroundStation/src/GroundStation/GroundStation/myUI/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(739, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_status = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_status)
        self.lineEdit_status = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_status.sizePolicy().hasHeightForWidth())
        self.lineEdit_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_status.setFont(font)
        self.lineEdit_status.setObjectName("lineEdit_status")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_status)
        self.label_pos = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pos.sizePolicy().hasHeightForWidth())
        self.label_pos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_pos.setFont(font)
        self.label_pos.setObjectName("label_pos")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_pos)
        self.lineEdit_pos = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pos.sizePolicy().hasHeightForWidth())
        self.lineEdit_pos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_pos.setFont(font)
        self.lineEdit_pos.setObjectName("lineEdit_pos")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pos)
        self.gridLayout_4.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_runtask = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_runtask.setFont(font)
        self.pushButton_runtask.setObjectName("pushButton_runtask")
        self.gridLayout.addWidget(self.pushButton_runtask, 0, 1, 1, 1)
        self.pushButton_takeoff = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_takeoff.sizePolicy().hasHeightForWidth())
        self.pushButton_takeoff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_takeoff.setFont(font)
        self.pushButton_takeoff.setObjectName("pushButton_takeoff")
        self.gridLayout.addWidget(self.pushButton_takeoff, 1, 0, 1, 1)
        self.pushButton_reset_task = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_reset_task.setFont(font)
        self.pushButton_reset_task.setObjectName("pushButton_reset_task")
        self.gridLayout.addWidget(self.pushButton_reset_task, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_task = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_task.setFont(font)
        self.lineEdit_task.setText("")
        self.lineEdit_task.setObjectName("lineEdit_task")
        self.gridLayout.addWidget(self.lineEdit_task, 2, 1, 1, 2)
        self.pushButton_land = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_land.sizePolicy().hasHeightForWidth())
        self.pushButton_land.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_land.setFont(font)
        self.pushButton_land.setObjectName("pushButton_land")
        self.gridLayout.addWidget(self.pushButton_land, 0, 2, 2, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_LED = QtWidgets.QPushButton(self.frame)
        self.pushButton_LED.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_LED.setFont(font)
        self.pushButton_LED.setAutoFillBackground(False)
        self.pushButton_LED.setStyleSheet("background-color: blue;color: rgb(0, 0, 0);")
        self.pushButton_LED.setObjectName("pushButton_LED")
        self.gridLayout_2.addWidget(self.pushButton_LED, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.textEdit_qrresult = QtWidgets.QTextEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_qrresult.setFont(font)
        self.textEdit_qrresult.setObjectName("textEdit_qrresult")
        self.gridLayout_2.addWidget(self.textEdit_qrresult, 1, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 2, 1, 1)
        self.frame_carmera = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_carmera.setFont(font)
        self.frame_carmera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carmera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carmera.setObjectName("frame_carmera")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_carmera)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_carmera)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_other = QtWidgets.QWidget()
        self.tab_other.setObjectName("tab_other")
        self.tabWidget.addTab(self.tab_other, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_qrtitle = QtWidgets.QLabel(self.frame_carmera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_qrtitle.sizePolicy().hasHeightForWidth())
        self.label_qrtitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_qrtitle.setFont(font)
        self.label_qrtitle.setObjectName("label_qrtitle")
        self.horizontalLayout.addWidget(self.label_qrtitle)
        self.lineEdit_qrcode = QtWidgets.QLineEdit(self.frame_carmera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_qrcode.sizePolicy().hasHeightForWidth())
        self.lineEdit_qrcode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_qrcode.setFont(font)
        self.lineEdit_qrcode.setText("")
        self.lineEdit_qrcode.setObjectName("lineEdit_qrcode")
        self.horizontalLayout.addWidget(self.lineEdit_qrcode)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_3.addWidget(self.frame_carmera, 0, 0, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 3)
        self.gridLayout_3.setColumnStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setGeometry(QtCore.QRect(479, 263, 208, 113))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.menu_1.setFont(font)
        self.menu_1.setObjectName("menu_1")
        self.menu_test = QtWidgets.QMenu(self.menubar)
        self.menu_test.setGeometry(QtCore.QRect(546, 263, 257, 97))
        self.menu_test.setObjectName("menu_test")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionClose.setFont(font)
        self.actionClose.setObjectName("actionClose")
        self.actionOpenSub = QtWidgets.QAction(MainWindow)
        self.actionOpenSub.setObjectName("actionOpenSub")
        self.actionHand = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionHand.setFont(font)
        self.actionHand.setObjectName("actionHand")
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.actionClose)
        self.menu_test.addAction(self.actionHand)
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_test.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_status.setText(_translate("MainWindow", "连接情况:"))
        self.label_pos.setText(_translate("MainWindow", "飞机位置:"))
        self.pushButton.setText(_translate("MainWindow", "起飞确认"))
        self.pushButton_runtask.setText(_translate("MainWindow", "开始任务"))
        self.pushButton_takeoff.setText(_translate("MainWindow", "起飞"))
        self.pushButton_reset_task.setText(_translate("MainWindow", "重置任务"))
        self.label_3.setText(_translate("MainWindow", "当前任务是："))
        self.pushButton_land.setText(_translate("MainWindow", "降落"))
        self.pushButton_LED.setText(_translate("MainWindow", "日志更新指示"))
        self.label_4.setText(_translate("MainWindow", "系统关键日志:"))
        self.textEdit_qrresult.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">测试文本</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_other), _translate("MainWindow", "其他"))
        self.label_qrtitle.setText(_translate("MainWindow", "摄像头识别到信息："))
        self.menu_1.setTitle(_translate("MainWindow", "菜单1"))
        self.menu_test.setTitle(_translate("MainWindow", "手动遥控"))
        self.actionClose.setText(_translate("MainWindow", "关闭/退出程序"))
        self.actionOpenSub.setText(_translate("MainWindow", "打开手动控制界面"))
        self.actionHand.setText(_translate("MainWindow", "飞机手动操作面板"))
