# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/focal/Desktop/2024_GroundStation/src/GroundStation/GroundStation/myUI/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1667, 1090)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_carmera = QtWidgets.QFrame(self.centralwidget)
        self.frame_carmera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carmera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_carmera.setObjectName("frame_carmera")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_carmera)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_carmera)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_qrcode_image = QtWidgets.QLabel(self.frame_carmera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_qrcode_image.sizePolicy().hasHeightForWidth())
        self.label_qrcode_image.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_qrcode_image.setFont(font)
        self.label_qrcode_image.setAcceptDrops(True)
        self.label_qrcode_image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_qrcode_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_qrcode_image.setScaledContents(True)
        self.label_qrcode_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_qrcode_image.setObjectName("label_qrcode_image")
        self.verticalLayout.addWidget(self.label_qrcode_image)
        self.label_qrtitle = QtWidgets.QLabel(self.frame_carmera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_qrtitle.sizePolicy().hasHeightForWidth())
        self.label_qrtitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_qrtitle.setFont(font)
        self.label_qrtitle.setObjectName("label_qrtitle")
        self.verticalLayout.addWidget(self.label_qrtitle)
        self.lineEdit_qrcode = QtWidgets.QLineEdit(self.frame_carmera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_qrcode.sizePolicy().hasHeightForWidth())
        self.lineEdit_qrcode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_qrcode.setFont(font)
        self.lineEdit_qrcode.setText("")
        self.lineEdit_qrcode.setObjectName("lineEdit_qrcode")
        self.verticalLayout.addWidget(self.lineEdit_qrcode)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_carmera)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_qrcode2_image = QtWidgets.QLabel(self.frame_carmera)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_qrcode2_image.setFont(font)
        self.label_qrcode2_image.setScaledContents(True)
        self.label_qrcode2_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_qrcode2_image.setObjectName("label_qrcode2_image")
        self.verticalLayout_2.addWidget(self.label_qrcode2_image)
        self.label_qrtitle_2 = QtWidgets.QLabel(self.frame_carmera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_qrtitle_2.sizePolicy().hasHeightForWidth())
        self.label_qrtitle_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_qrtitle_2.setFont(font)
        self.label_qrtitle_2.setObjectName("label_qrtitle_2")
        self.verticalLayout_2.addWidget(self.label_qrtitle_2)
        self.lineEdit_qrcode2 = QtWidgets.QLineEdit(self.frame_carmera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_qrcode2.sizePolicy().hasHeightForWidth())
        self.lineEdit_qrcode2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_qrcode2.setFont(font)
        self.lineEdit_qrcode2.setText("")
        self.lineEdit_qrcode2.setObjectName("lineEdit_qrcode2")
        self.verticalLayout_2.addWidget(self.lineEdit_qrcode2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addWidget(self.frame_carmera, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton_takeoff = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_takeoff.sizePolicy().hasHeightForWidth())
        self.pushButton_takeoff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_takeoff.setFont(font)
        self.pushButton_takeoff.setObjectName("pushButton_takeoff")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_takeoff)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_status = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_status)
        self.lineEdit_status = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_status.sizePolicy().hasHeightForWidth())
        self.lineEdit_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_status.setFont(font)
        self.lineEdit_status.setObjectName("lineEdit_status")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_status)
        self.label_pos = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pos.sizePolicy().hasHeightForWidth())
        self.label_pos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_pos.setFont(font)
        self.label_pos.setObjectName("label_pos")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_pos)
        self.lineEdit_pos = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pos.sizePolicy().hasHeightForWidth())
        self.lineEdit_pos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_pos.setFont(font)
        self.lineEdit_pos.setObjectName("lineEdit_pos")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pos)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.pushButton_land = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_land.sizePolicy().hasHeightForWidth())
        self.pushButton_land.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_land.setFont(font)
        self.pushButton_land.setObjectName("pushButton_land")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pushButton_land)
        self.pushButton_runtask = QtWidgets.QPushButton(self.frame)
        self.pushButton_runtask.setObjectName("pushButton_runtask")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.pushButton_runtask)
        self.gridLayout_3.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1667, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.menu_1.setFont(font)
        self.menu_1.setObjectName("menu_1")
        self.menu_test = QtWidgets.QMenu(self.menubar)
        self.menu_test.setObjectName("menu_test")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpenSub = QtWidgets.QAction(MainWindow)
        self.actionOpenSub.setObjectName("actionOpenSub")
        self.actionHand = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.actionHand.setFont(font)
        self.actionHand.setObjectName("actionHand")
        self.menu_1.addAction(self.actionClose)
        self.menu_test.addAction(self.actionHand)
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_test.menuAction())

        self.retranslateUi(MainWindow)
        self.actionClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "video0画面浏览-机身尾部"))
        self.label_qrcode_image.setText(_translate("MainWindow", "video0画面浏览"))
        self.label_qrtitle.setText(_translate("MainWindow", "video0识别到的QR码"))
        self.label_2.setText(_translate("MainWindow", "video2画面浏览-机身头部"))
        self.label_qrcode2_image.setText(_translate("MainWindow", "video2画面浏览"))
        self.label_qrtitle_2.setText(_translate("MainWindow", "video2识别到的QR码"))
        self.pushButton_takeoff.setText(_translate("MainWindow", "起飞"))
        self.label_status.setText(_translate("MainWindow", "连接情况:"))
        self.label_pos.setText(_translate("MainWindow", "飞机位置:"))
        self.pushButton.setText(_translate("MainWindow", "起飞确认"))
        self.pushButton_land.setText(_translate("MainWindow", "降落"))
        self.pushButton_runtask.setText(_translate("MainWindow", "执行任务"))
        self.menu_1.setTitle(_translate("MainWindow", "菜单1"))
        self.menu_test.setTitle(_translate("MainWindow", "其他"))
        self.actionClose.setText(_translate("MainWindow", "关闭/退出程序"))
        self.actionOpenSub.setText(_translate("MainWindow", "打开手动控制界面"))
        self.actionHand.setText(_translate("MainWindow", "手动操作面板"))
