# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/focal/Desktop/2024_GroundStation/src/GroundStation/GroundStation/myUI/subDialog1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_subDialog1(object):
    def setupUi(self, subDialog1):
        subDialog1.setObjectName("subDialog1")
        subDialog1.resize(720, 504)
        self.gridLayout_2 = QtWidgets.QGridLayout(subDialog1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_pos = QtWidgets.QLabel(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_pos.setFont(font)
        self.label_pos.setObjectName("label_pos")
        self.gridLayout_2.addWidget(self.label_pos, 0, 0, 1, 1)
        self.lineEdit_pos = QtWidgets.QLineEdit(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_pos.setFont(font)
        self.lineEdit_pos.setObjectName("lineEdit_pos")
        self.gridLayout_2.addWidget(self.lineEdit_pos, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 1, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_forward = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_forward.setFont(font)
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.gridLayout.addWidget(self.pushButton_forward, 0, 1, 1, 1)
        self.pushButton_turn_left = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_turn_left.setFont(font)
        self.pushButton_turn_left.setObjectName("pushButton_turn_left")
        self.gridLayout.addWidget(self.pushButton_turn_left, 0, 0, 1, 1)
        self.pushButton_landnormal = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_landnormal.setFont(font)
        self.pushButton_landnormal.setObjectName("pushButton_landnormal")
        self.gridLayout.addWidget(self.pushButton_landnormal, 3, 2, 1, 1)
        self.pushButton_closeDialog = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_closeDialog.setFont(font)
        self.pushButton_closeDialog.setObjectName("pushButton_closeDialog")
        self.gridLayout.addWidget(self.pushButton_closeDialog, 4, 2, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_left.setFont(font)
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout.addWidget(self.pushButton_left, 1, 0, 1, 1)
        self.pushButton_hover = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_hover.setFont(font)
        self.pushButton_hover.setObjectName("pushButton_hover")
        self.gridLayout.addWidget(self.pushButton_hover, 1, 1, 1, 1)
        self.pushButton_right = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_right.setFont(font)
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout.addWidget(self.pushButton_right, 1, 2, 1, 1)
        self.pushButton_down = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_down.setFont(font)
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout.addWidget(self.pushButton_down, 2, 2, 1, 1)
        self.pushButton_fly = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_fly.setFont(font)
        self.pushButton_fly.setObjectName("pushButton_fly")
        self.gridLayout.addWidget(self.pushButton_fly, 4, 0, 1, 1)
        self.pushButton_up = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_up.setFont(font)
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout.addWidget(self.pushButton_up, 2, 0, 1, 1)
        self.pushButton_flyagain = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_flyagain.setFont(font)
        self.pushButton_flyagain.setObjectName("pushButton_flyagain")
        self.gridLayout.addWidget(self.pushButton_flyagain, 4, 1, 1, 1)
        self.pushButton_back = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 2, 1, 1, 1)
        self.pushButton_turn_right = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_turn_right.setFont(font)
        self.pushButton_turn_right.setObjectName("pushButton_turn_right")
        self.gridLayout.addWidget(self.pushButton_turn_right, 0, 2, 1, 1)
        self.pushButton_stopland = QtWidgets.QPushButton(subDialog1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_stopland.setFont(font)
        self.pushButton_stopland.setObjectName("pushButton_stopland")
        self.gridLayout.addWidget(self.pushButton_stopland, 3, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 2)

        self.retranslateUi(subDialog1)
        self.pushButton_closeDialog.clicked.connect(subDialog1.hide)
        QtCore.QMetaObject.connectSlotsByName(subDialog1)

    def retranslateUi(self, subDialog1):
        _translate = QtCore.QCoreApplication.translate
        subDialog1.setWindowTitle(_translate("subDialog1", "Dialog"))
        self.label_pos.setText(_translate("subDialog1", "飞机当前位置:"))
        self.checkBox.setText(_translate("subDialog1", "舵机上锁悬挂/解锁下放"))
        self.pushButton_forward.setText(_translate("subDialog1", "前"))
        self.pushButton_turn_left.setText(_translate("subDialog1", "左转"))
        self.pushButton_landnormal.setText(_translate("subDialog1", "正常降落"))
        self.pushButton_closeDialog.setText(_translate("subDialog1", "关闭此页面"))
        self.pushButton_left.setText(_translate("subDialog1", "左"))
        self.pushButton_hover.setText(_translate("subDialog1", "悬停"))
        self.pushButton_right.setText(_translate("subDialog1", "右"))
        self.pushButton_down.setText(_translate("subDialog1", "下降"))
        self.pushButton_fly.setText(_translate("subDialog1", "起飞"))
        self.pushButton_up.setText(_translate("subDialog1", "上升"))
        self.pushButton_flyagain.setText(_translate("subDialog1", "再起飞"))
        self.pushButton_back.setText(_translate("subDialog1", "后"))
        self.pushButton_turn_right.setText(_translate("subDialog1", "右转"))
        self.pushButton_stopland.setText(_translate("subDialog1", "急停降落"))
