# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/focal/Desktop/2024_GroundStation/src/GroundStation/GroundStation/myUI/subDialog1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_subDialog1(object):
    def setupUi(self, subDialog1):
        subDialog1.setObjectName("subDialog1")
        subDialog1.resize(820, 655)
        self.gridLayoutWidget = QtWidgets.QWidget(subDialog1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(240, 90, 271, 278))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_hover = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_hover.setFont(font)
        self.pushButton_hover.setObjectName("pushButton_hover")
        self.gridLayout.addWidget(self.pushButton_hover, 1, 1, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_left.setFont(font)
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout.addWidget(self.pushButton_left, 1, 0, 1, 1)
        self.pushButton_turn_left = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_turn_left.setFont(font)
        self.pushButton_turn_left.setObjectName("pushButton_turn_left")
        self.gridLayout.addWidget(self.pushButton_turn_left, 0, 0, 1, 1)
        self.pushButton_turn_right = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_turn_right.setFont(font)
        self.pushButton_turn_right.setObjectName("pushButton_turn_right")
        self.gridLayout.addWidget(self.pushButton_turn_right, 0, 2, 1, 1)
        self.pushButton_forward = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_forward.setFont(font)
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.gridLayout.addWidget(self.pushButton_forward, 0, 1, 1, 1)
        self.pushButton_right = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_right.setFont(font)
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout.addWidget(self.pushButton_right, 1, 2, 1, 1)
        self.pushButton_stopland = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_stopland.setFont(font)
        self.pushButton_stopland.setObjectName("pushButton_stopland")
        self.gridLayout.addWidget(self.pushButton_stopland, 4, 0, 1, 3)
        self.pushButton_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_up.setFont(font)
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout.addWidget(self.pushButton_up, 2, 0, 1, 1)
        self.pushButton_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_down.setFont(font)
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout.addWidget(self.pushButton_down, 2, 2, 1, 1)
        self.pushButton_flyagain = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_flyagain.setFont(font)
        self.pushButton_flyagain.setObjectName("pushButton_flyagain")
        self.gridLayout.addWidget(self.pushButton_flyagain, 5, 0, 1, 3)
        self.pushButton_back = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(subDialog1)
        self.label.setGeometry(QtCore.QRect(320, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setObjectName("label")
        self.pushButton_closeDialog = QtWidgets.QPushButton(subDialog1)
        self.pushButton_closeDialog.setGeometry(QtCore.QRect(690, 610, 111, 31))
        self.pushButton_closeDialog.setObjectName("pushButton_closeDialog")
        self.label_pos = QtWidgets.QLabel(subDialog1)
        self.label_pos.setGeometry(QtCore.QRect(50, 50, 94, 25))
        self.label_pos.setObjectName("label_pos")
        self.lineEdit_pos = QtWidgets.QLineEdit(subDialog1)
        self.lineEdit_pos.setGeometry(QtCore.QRect(160, 50, 441, 25))
        self.lineEdit_pos.setObjectName("lineEdit_pos")
        self.tableWidget = QtWidgets.QTableWidget(subDialog1)
        self.tableWidget.setGeometry(QtCore.QRect(30, 380, 331, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        self.lineEdit_yp = QtWidgets.QLineEdit(subDialog1)
        self.lineEdit_yp.setGeometry(QtCore.QRect(450, 430, 199, 25))
        self.lineEdit_yp.setObjectName("lineEdit_yp")
        self.lineEdit_xp = QtWidgets.QLineEdit(subDialog1)
        self.lineEdit_xp.setGeometry(QtCore.QRect(450, 390, 199, 25))
        self.lineEdit_xp.setObjectName("lineEdit_xp")
        self.lineEdit_zp = QtWidgets.QLineEdit(subDialog1)
        self.lineEdit_zp.setGeometry(QtCore.QRect(450, 470, 199, 25))
        self.lineEdit_zp.setObjectName("lineEdit_zp")
        self.label_5 = QtWidgets.QLabel(subDialog1)
        self.label_5.setGeometry(QtCore.QRect(400, 390, 44, 25))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(subDialog1)
        self.label_6.setGeometry(QtCore.QRect(400, 470, 44, 25))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(subDialog1)
        self.label_7.setGeometry(QtCore.QRect(400, 430, 44, 25))
        self.label_7.setObjectName("label_7")
        self.pushButton_upset = QtWidgets.QPushButton(subDialog1)
        self.pushButton_upset.setGeometry(QtCore.QRect(390, 540, 141, 31))
        self.pushButton_upset.setObjectName("pushButton_upset")
        self.pushButton_downset = QtWidgets.QPushButton(subDialog1)
        self.pushButton_downset.setGeometry(QtCore.QRect(390, 580, 141, 31))
        self.pushButton_downset.setObjectName("pushButton_downset")
        self.pushButton_insertset = QtWidgets.QPushButton(subDialog1)
        self.pushButton_insertset.setGeometry(QtCore.QRect(540, 540, 141, 31))
        self.pushButton_insertset.setObjectName("pushButton_insertset")
        self.pushButton_deleteset = QtWidgets.QPushButton(subDialog1)
        self.pushButton_deleteset.setGeometry(QtCore.QRect(540, 580, 141, 31))
        self.pushButton_deleteset.setObjectName("pushButton_deleteset")

        self.retranslateUi(subDialog1)
        self.pushButton_closeDialog.clicked.connect(subDialog1.hide)
        QtCore.QMetaObject.connectSlotsByName(subDialog1)

    def retranslateUi(self, subDialog1):
        _translate = QtCore.QCoreApplication.translate
        subDialog1.setWindowTitle(_translate("subDialog1", "Dialog"))
        self.pushButton_hover.setText(_translate("subDialog1", "悬停"))
        self.pushButton_left.setText(_translate("subDialog1", "左"))
        self.pushButton_turn_left.setText(_translate("subDialog1", "左转"))
        self.pushButton_turn_right.setText(_translate("subDialog1", "右转"))
        self.pushButton_forward.setText(_translate("subDialog1", "前"))
        self.pushButton_right.setText(_translate("subDialog1", "右"))
        self.pushButton_stopland.setText(_translate("subDialog1", "急停降落"))
        self.pushButton_up.setText(_translate("subDialog1", "上升"))
        self.pushButton_down.setText(_translate("subDialog1", "下降"))
        self.pushButton_flyagain.setText(_translate("subDialog1", "再次起飞"))
        self.pushButton_back.setText(_translate("subDialog1", "后"))
        self.label.setText(_translate("subDialog1", "手动控制模式"))
        self.pushButton_closeDialog.setText(_translate("subDialog1", "关闭此页面"))
        self.label_pos.setText(_translate("subDialog1", "飞机当前位置:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("subDialog1", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("subDialog1", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("subDialog1", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("subDialog1", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("subDialog1", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("subDialog1", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("subDialog1", "7"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("subDialog1", "X(cm)"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("subDialog1", "Y(cm)"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("subDialog1", "Z(cm)"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("subDialog1", "0"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("subDialog1", "0"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("subDialog1", "0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("subDialog1", "40"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("subDialog1", "40"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("subDialog1", "50"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("subDialog1", "X坐标:"))
        self.label_6.setText(_translate("subDialog1", "Z坐标"))
        self.label_7.setText(_translate("subDialog1", "Y坐标:"))
        self.pushButton_upset.setText(_translate("subDialog1", "上移"))
        self.pushButton_downset.setText(_translate("subDialog1", "下移"))
        self.pushButton_insertset.setText(_translate("subDialog1", "插入"))
        self.pushButton_deleteset.setText(_translate("subDialog1", "删除"))
